version: '3'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.12.1"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      http.cors.enabled: "true"
      http.cors.allow-origin: http://localhost:1358,http://127.0.0.1:1358
      http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      http.cors.allow-credentials: "true"
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.12.1"
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
  dejavu:
    image: appbaseio/dejavu
    ports:
      - "1358:1358"