version: '3'
services:
  fluentd:
    container_name: fluentd
    user: root
    build:
      context: .
    image: fluentd
    volumes:
    - ./file:/fluentd/log/files/ #Example: Reading logs from a file
    - ./config:/fluentd/etc/
    - ./output-log:/output/ # Example: Fluentd will collect logs and store it here for demo
    logging:
      driver: "local"
  # This app writes logs to a local file
  file-myapp:
    container_name: file-myapp
    image: alpine
    volumes:
    - ./file:/app
    command: [ /bin/sh , -c , "chmod +x /app/app.sh && ./app/app.sh"]