version: '3'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.11.1"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.11.1"
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
  fluentd:
    build: ./fluentd-build
    image: "fluent/fluentd:edge"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  myapp:
    image: "demo:0.0.1-SNAPSHOT"
    ports:
      - "8080:8080"
    logging:
      driver: "fluentd"
      options: 
        fluentd-address: localhost:24224
        tag: myapp
    depends_on: 
      - fluentd
