apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.13.4
  http:
    service:
      spec:
        type: LoadBalancer
  nodeSets:
  - name: default
    count: 1
    podTemplate: 
      metadata:
        labels:
          app: elasticsearch
    config:
      node.store.allow_mmap: false
