version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.11.1"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      # discovery.type: single-node
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch,elasticsearch2
      - cluster.initial_master_nodes=elasticsearch,elasticsearch2,elasticsearch3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.store.allow_mmap=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
  elasticsearch2:
    container_name: elasticsearch2
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.11.1"
    # ports:
    #   - "9200:9200"
    #   - "9300:9300"
    environment:
      # discovery.type: single-node
      - node.name=elasticsearch2
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch2,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch,elasticsearch2,elasticsearch3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.store.allow_mmap=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
  elasticsearch3:
    container_name: elasticsearch3
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.11.1"
    # ports:
    #   - "9200:9200"
    #   - "9300:9300"
    environment:
      # discovery.type: single-node
      - node.name=elasticsearch3
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch,elasticsearch2
      - cluster.initial_master_nodes=elasticsearch,elasticsearch2,elasticsearch3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.store.allow_mmap=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.11.1"
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
